
package org.wso2.carbon.um.ws.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.8
 * 2020-12-31T20:26:42.425+05:30
 * Generated source version: 3.3.8
 *
 */
public final class RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.um.carbon.wso2.org", "RemoteUserStoreManagerService");

    private RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RemoteUserStoreManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RemoteUserStoreManagerService ss = new RemoteUserStoreManagerService(wsdlURL, SERVICE_NAME);
        RemoteUserStoreManagerServicePortType port = ss.getRemoteUserStoreManagerServiceHttpsEndpoint();

        {
        System.out.println("Invoking getTenantId...");
        try {
            java.lang.Integer _getTenantId__return = port.getTenantId();
            System.out.println("getTenantId.result=" + _getTenantId__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteRole...");
        org.wso2.carbon.um.ws.service.DeleteRole _deleteRole_parameters = null;
        try {
            port.deleteRole(_deleteRole_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isExistingRole...");
        java.lang.String _isExistingRole_roleName = "";
        try {
            java.lang.Boolean _isExistingRole__return = port.isExistingRole(_isExistingRole_roleName);
            System.out.println("isExistingRole.result=" + _isExistingRole__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getProperties...");
        org.wso2.carbon.user.core.tenant.xsd.Tenant _getProperties_tenant = null;
        try {
            java.util.List<org.wso2.carbon.um.ws.service.ArrayOfString> _getProperties__return = port.getProperties(_getProperties_tenant);
            System.out.println("getProperties.result=" + _getProperties__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserListOfRole...");
        java.lang.String _getUserListOfRole_roleName = "";
        try {
            java.util.List<java.lang.String> _getUserListOfRole__return = port.getUserListOfRole(_getUserListOfRole_roleName);
            System.out.println("getUserListOfRole.result=" + _getUserListOfRole__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateUserListOfRole...");
        org.wso2.carbon.um.ws.service.UpdateUserListOfRole _updateUserListOfRole_parameters = null;
        try {
            port.updateUserListOfRole(_updateUserListOfRole_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking addUserClaimValue...");
        org.wso2.carbon.um.ws.service.AddUserClaimValue _addUserClaimValue_parameters = null;
        try {
            port.addUserClaimValue(_addUserClaimValue_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateRoleName...");
        org.wso2.carbon.um.ws.service.UpdateRoleName _updateRoleName_parameters = null;
        try {
            port.updateRoleName(_updateRoleName_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking addRole...");
        org.wso2.carbon.um.ws.service.AddRole _addRole_parameters = null;
        try {
            port.addRole(_addRole_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserId...");
        java.lang.String _getUserId_username = "";
        try {
            java.lang.Integer _getUserId__return = port.getUserId(_getUserId_username);
            System.out.println("getUserId.result=" + _getUserId__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteUser...");
        org.wso2.carbon.um.ws.service.DeleteUser _deleteUser_parameters = null;
        try {
            port.deleteUser(_deleteUser_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getProfileNames...");
        java.lang.String _getProfileNames_userName = "";
        try {
            java.util.List<java.lang.String> _getProfileNames__return = port.getProfileNames(_getProfileNames_userName);
            System.out.println("getProfileNames.result=" + _getProfileNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserClaimValues...");
        java.lang.String _getUserClaimValues_userName = "";
        java.lang.String _getUserClaimValues_profileName = "";
        try {
            java.util.List<org.wso2.carbon.um.ws.service.dao.xsd.ClaimDTO> _getUserClaimValues__return = port.getUserClaimValues(_getUserClaimValues_userName, _getUserClaimValues_profileName);
            System.out.println("getUserClaimValues.result=" + _getUserClaimValues__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking setUserClaimValue...");
        org.wso2.carbon.um.ws.service.SetUserClaimValue _setUserClaimValue_parameters = null;
        try {
            port.setUserClaimValue(_setUserClaimValue_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getTenantIdofUser...");
        java.lang.String _getTenantIdofUser_username = "";
        try {
            java.lang.Integer _getTenantIdofUser__return = port.getTenantIdofUser(_getTenantIdofUser_username);
            System.out.println("getTenantIdofUser.result=" + _getTenantIdofUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserClaimValue...");
        java.lang.String _getUserClaimValue_userName = "";
        java.lang.String _getUserClaimValue_claim = "";
        java.lang.String _getUserClaimValue_profileName = "";
        try {
            java.lang.String _getUserClaimValue__return = port.getUserClaimValue(_getUserClaimValue_userName, _getUserClaimValue_claim, _getUserClaimValue_profileName);
            System.out.println("getUserClaimValue.result=" + _getUserClaimValue__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listUsers...");
        java.lang.String _listUsers_filter = "";
        java.lang.Integer _listUsers_maxItemLimit = null;
        try {
            java.util.List<java.lang.String> _listUsers__return = port.listUsers(_listUsers_filter, _listUsers_maxItemLimit);
            System.out.println("listUsers.result=" + _listUsers__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateCredentialByAdmin...");
        org.wso2.carbon.um.ws.service.UpdateCredentialByAdmin _updateCredentialByAdmin_parameters = null;
        try {
            port.updateCredentialByAdmin(_updateCredentialByAdmin_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getAllProfileNames...");
        try {
            java.util.List<java.lang.String> _getAllProfileNames__return = port.getAllProfileNames();
            System.out.println("getAllProfileNames.result=" + _getAllProfileNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getRoleListOfUser...");
        java.lang.String _getRoleListOfUser_userName = "";
        try {
            java.util.List<java.lang.String> _getRoleListOfUser__return = port.getRoleListOfUser(_getRoleListOfUser_userName);
            System.out.println("getRoleListOfUser.result=" + _getRoleListOfUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserList...");
        java.lang.String _getUserList_claimUri = "";
        java.lang.String _getUserList_claimValue = "";
        java.lang.String _getUserList_profile = "";
        try {
            java.util.List<java.lang.String> _getUserList__return = port.getUserList(_getUserList_claimUri, _getUserList_claimValue, _getUserList_profile);
            System.out.println("getUserList.result=" + _getUserList__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking addUserClaimValues...");
        org.wso2.carbon.um.ws.service.AddUserClaimValues _addUserClaimValues_parameters = null;
        try {
            port.addUserClaimValues(_addUserClaimValues_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isExistingUser...");
        java.lang.String _isExistingUser_userName = "";
        try {
            java.lang.Boolean _isExistingUser__return = port.isExistingUser(_isExistingUser_userName);
            System.out.println("isExistingUser.result=" + _isExistingUser__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking addUser...");
        org.wso2.carbon.um.ws.service.AddUser _addUser_parameters = null;
        try {
            port.addUser(_addUser_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateRoleListOfUser...");
        org.wso2.carbon.um.ws.service.UpdateRoleListOfUser _updateRoleListOfUser_parameters = null;
        try {
            port.updateRoleListOfUser(_updateRoleListOfUser_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteUserClaimValues...");
        org.wso2.carbon.um.ws.service.DeleteUserClaimValues _deleteUserClaimValues_parameters = null;
        try {
            port.deleteUserClaimValues(_deleteUserClaimValues_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getRoleNames...");
        try {
            java.util.List<java.lang.String> _getRoleNames__return = port.getRoleNames();
            System.out.println("getRoleNames.result=" + _getRoleNames__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateCredential...");
        org.wso2.carbon.um.ws.service.UpdateCredential _updateCredential_parameters = null;
        try {
            port.updateCredential(_updateCredential_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking authenticate...");
        java.lang.String _authenticate_userName = "";
        java.lang.String _authenticate_credential = "";
        try {
            java.lang.Boolean _authenticate__return = port.authenticate(_authenticate_userName, _authenticate_credential);
            System.out.println("authenticate.result=" + _authenticate__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getPasswordExpirationTime...");
        java.lang.String _getPasswordExpirationTime_username = "";
        try {
            java.lang.Long _getPasswordExpirationTime__return = port.getPasswordExpirationTime(_getPasswordExpirationTime_username);
            System.out.println("getPasswordExpirationTime.result=" + _getPasswordExpirationTime__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUserClaimValuesForClaims...");
        java.lang.String _getUserClaimValuesForClaims_userName = "";
        java.util.List<java.lang.String> _getUserClaimValuesForClaims_claims = null;
        java.lang.String _getUserClaimValuesForClaims_profileName = "";
        try {
            java.util.List<org.wso2.carbon.user.mgt.common.xsd.ClaimValue> _getUserClaimValuesForClaims__return = port.getUserClaimValuesForClaims(_getUserClaimValuesForClaims_userName, _getUserClaimValuesForClaims_claims, _getUserClaimValuesForClaims_profileName);
            System.out.println("getUserClaimValuesForClaims.result=" + _getUserClaimValuesForClaims__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking setUserClaimValues...");
        org.wso2.carbon.um.ws.service.SetUserClaimValues _setUserClaimValues_parameters = null;
        try {
            port.setUserClaimValues(_setUserClaimValues_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteUserClaimValue...");
        org.wso2.carbon.um.ws.service.DeleteUserClaimValue _deleteUserClaimValue_parameters = null;
        try {
            port.deleteUserClaimValue(_deleteUserClaimValue_parameters);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isReadOnly...");
        try {
            java.lang.Boolean _isReadOnly__return = port.isReadOnly();
            System.out.println("isReadOnly.result=" + _isReadOnly__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getHybridRoles...");
        try {
            java.util.List<java.lang.String> _getHybridRoles__return = port.getHybridRoles();
            System.out.println("getHybridRoles.result=" + _getHybridRoles__return);

        } catch (RemoteUserStoreManagerServiceUserStoreException_Exception e) {
            System.out.println("Expected exception: RemoteUserStoreManagerServiceUserStoreException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
