
package org.wso2.carbon.um.ws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.8
 * 2020-12-31T20:26:42.507+05:30
 * Generated source version: 3.3.8
 */

@WebFault(name = "RemoteUserStoreManagerServiceUserStoreException", targetNamespace = "http://service.ws.um.carbon.wso2.org")
public class RemoteUserStoreManagerServiceUserStoreException_Exception extends Exception {

    private org.wso2.carbon.um.ws.service.RemoteUserStoreManagerServiceUserStoreException faultInfo;

    public RemoteUserStoreManagerServiceUserStoreException_Exception() {
        super();
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message) {
        super(message);
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, org.wso2.carbon.um.ws.service.RemoteUserStoreManagerServiceUserStoreException remoteUserStoreManagerServiceUserStoreException) {
        super(message);
        this.faultInfo = remoteUserStoreManagerServiceUserStoreException;
    }

    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, org.wso2.carbon.um.ws.service.RemoteUserStoreManagerServiceUserStoreException remoteUserStoreManagerServiceUserStoreException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = remoteUserStoreManagerServiceUserStoreException;
    }

    public org.wso2.carbon.um.ws.service.RemoteUserStoreManagerServiceUserStoreException getFaultInfo() {
        return this.faultInfo;
    }
}
