
package org.wso2.carbon.um.ws.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.8
 * 2020-12-31T20:26:42.634+05:30
 * Generated source version: 3.3.8
 *
 */

public class RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsSoap11Endpoint_Server{

    protected RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsSoap11Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new RemoteUserStoreManagerServiceHttpsSoap11EndpointImpl();
        String address = "https://localhost:9443/services/RemoteUserStoreManagerService.RemoteUserStoreManagerServiceHttpsSoap11Endpoint/";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new RemoteUserStoreManagerServicePortType_RemoteUserStoreManagerServiceHttpsSoap11Endpoint_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
